%{
    wksp2MasterParma_CopyPaste.m
    02/08/2020
    C. Rovin

    Script to take the workspace (populated after running main_single.m)
    and create an excel document that is ordered identically to the 
    formatting of MasterParamFile.xlsx.

    To Use:
         1) Run "wksp2MasterParma_CopyPaste" after running main_single.m.
            Alternatively can copy "wksp2MasterParma_CopyPaste" into
            main_single.m at the bottom.
         2) Open the parameter excel document created by this script
         (named:*datetime*_Params.xlsx)
         3) Copy/Paste the variables into MasterParamFile.xlsx

%}

%% Create Column of Parameter Values (doubles)
ParamValues = {''  ;  (MRW-3000)  ;  MRW  ;  MZFW  ;  MLDW  ;  ...
               WFuel_calc ; WEmpty ; WPayload ; WWingStuff ; WFuse_unit*lFuse ; ...
               W_IPPS ; WEngClimb_IPPS ; WEng ; WPayload*1.5 ; '' ; ...
               AR ; AWing ; span ; span_overall ; sweep ; ...
               taper ; Cr ; MAC ; Ct ; '' ; ...
               lFuse ; dFuse ; lNose ; lTail ; AHtail ; ...
               'TBD' ; 'TBD' ; AVtail ; 'TBD' ; 'TBD' ; ...
               '' ; Neng ; Thrust_TO ; TW_IPPS ; WEngTO_IPPS ; ...
               dFan ; dNacel ; lNacel ; TO_eqThrust ; SFC ; ...
               '' ; Nz ; TC_avg ; sweep ; WWingSTR ; ...
               WWingStuff ; '' ; AWing_wet ; AHtail_wet ; AVtail_wet ; ...
               rNose ; hNose ; ogive_Rn ; ogive_Dn ; ANose_ogive ; ...
               ABarrel ; rTail ; hTail ; ogive_Rt ; ogive_Dt ; ...
               ATail_ogive ; AFuse_wet ; ANacel_wet ; Atotal_wet ; SwetSref ; ...
               Reft ; Re ; '' ; 'TBD' ; 'TBD' ; ...
               'TBD' ; '' ; Mach ; Altitude} ; 
%% Create a Table with the parameters
CopyPasteParams = table(ParamValues) ; 
saveName        = [datestr(datetime),'_params.xlsx'] ; 
saveName        = strrep(saveName,':','') ; 
saveName        = strrep(saveName,' ','-') ; 
%save excel in local directory with the values
%(first row corresponds to 'weights' in master parameter file --> it is
% left blank)
writetable(CopyPasteParams,saveName)